"""opening table

Revision ID: 57983659e09a
Revises: f6c2cd989a82
Create Date: 2021-05-06 14:11:00.953669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57983659e09a'
down_revision = 'f6c2cd989a82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('openings',
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('FEN', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('openings')
    # ### end Alembic commands ###
