"""add feedback

Revision ID: 801f488909e5
Revises: 04b74256dbfd
Create Date: 2021-05-14 13:21:24.546650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801f488909e5'
down_revision = '04b74256dbfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('feedback', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'feedback')
    # ### end Alembic commands ###
