"""feedback

Revision ID: bdda6dd43217
Revises: c0f50ee895d7
Create Date: 2021-05-14 13:48:09.810270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdda6dd43217'
down_revision = 'c0f50ee895d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('feedback', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'feedback')
    # ### end Alembic commands ###
