"""remove feedback

Revision ID: c0f50ee895d7
Revises: 801f488909e5
Create Date: 2021-05-14 13:37:21.663106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0f50ee895d7'
down_revision = '801f488909e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'feedback')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('feedback', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
