"""opening table

Revision ID: effaee8612a2
Revises: 04b74256dbfd
Create Date: 2021-05-12 15:29:33.420440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'effaee8612a2'
down_revision = '04b74256dbfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('openings', sa.Column('black', sa.Boolean(), nullable=False))
    op.alter_column('openings', 'FEN',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
    op.alter_column('openings', 'name',
               existing_type=sa.VARCHAR(length=140),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('openings', 'name',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
    op.alter_column('openings', 'FEN',
               existing_type=sa.VARCHAR(length=140),
               nullable=True)
    op.drop_column('openings', 'black')
    # ### end Alembic commands ###
